app/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # text redactor plugin
    url(r'^summernote/', include('django_summernote.urls')),
    # media
    url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
    # BLOG URLS
    url(r'', include(('blog.urls', 'blog'), namespace='blog')),

]

blog/urls.py
from django.conf.urls import url
from django.urls import include

from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^add_article/', views.add_article, name="add_article"),
    url(r'^register/', views.register, name="register"),
    url(r'^login/', views.login, name="login"),
    url(r'^logout/', views.logout, name="logout"),
    # url(r'^up_down/', views.up_down),
    # url(r'^comment/', views.comment),
    # url(r'^comment_tree/(\d+)/', views.comment_tree),
    # url(r'^(\w+)/article/(\d+)/$', views.article_detail),
    url(r'^$', views.home, name="home")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/breadcrumbs.html
<div class="breadcrumb-wrapper">
    <a href="{% url "blog:home" %}" class="breadcrumb">Блог</a>
    {% if request.path == '/add_article/' %}
        <a href="{% url "blog:add_article" %}" class="breadcrumb">
            <span class="slash">/</span>
            Добавить статью
        </a>
    {% elif request.path == '/register/' %}
        <a href="{% url "blog:register" %}" class="breadcrumb">
            <span class="slash">/</span>
            Регистрация
        </a>
    {% elif request.path == '/login/' %}
        <a href="{% url "blog:login" %}" class="breadcrumb">
            <span class="slash">/</span>
            Логин
        </a>
    {% endif %}
</div>

templates/includes/header.html
{% load static %}
<div class="row col s12">
    <div class="row left-hd-area col s7 ">
        <div class="logo-area flex">
            <a href="{% url 'blog:home' %}">
                <img src="{% static 'image/logo.svg' %}" alt="logo">
            </a>
            {% include "includes/breadcrumbs.html" %}
        </div>
    </div>
    <div class="row user-info col s5 ">
        <div class="row col s12">
            <div class="gretting-user col s8 center">
                <div class="settings-user flx-panel">
                    <div class="nav-wrapper">
                        <nav class="blue accent-4">
                            <div class="nav-wrapper">
                                <ul class="right hide-on-small-and-down">
                                    {% if user.is_authenticated %}
                                        {% if request.path == '/add_article/' %}
                                            <li><a href="{% url 'blog:home' %}">Главная</a></li>
                                        {% else %}
                                            <li><a href="{% url 'blog:add_article' %}">Создать статью</a></li>
                                        {% endif %}
                                    {% else %}
                                        <li><a href="{% url 'blog:login' %}">Вход</a></li>
                                        <li><a href="{% url 'blog:register' %}">Регистрация</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="settings-user col s4 flx-panel">
                {% if user.is_authenticated %}
                    <img src="{% static 'image/email.svg' %}" alt="message" class="message-icon">
                    <div class="avatar-area">
                        <img src="{{ user.avatar }}">
                    </div>
                    <a href="{% url "blog:logout" %}">
                        <img src="{% static 'image/logout.svg' %}" alt="message" class="logout-icon">
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/includes/interactive_icon.html
{% load static %}
<div>
    <img src="{% static 'image/like.svg' %}" alt="like">
    <span>25</span>
</div>
<div>
    <img src="{% static 'image/comment.svg' %}" alt="comment">
    <span>25</span>
</div>
<div>
    <img src="{% static 'image/view.svg' %}" alt="view">
    <span>25</span>
</div>